# Generated by Django 5.2.17 on 2026-09-08 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StakingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('lock_duration_days', models.PositiveIntegerField(default=30)),
                ('reward_rate_bps', models.PositiveIntegerField(default=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('claimed_reward', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staking_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(blank=True, max_length=255)),
                ('tx_type', models.CharField(choices=[('TICKET_PURCHASE', 'Ticket Purchase'), ('NFT_PURCHASE', 'NFT Purchase'), ('STAKE', 'Stake'), ('UNSTAKE', 'Unstake'), ('REWARD_CLAIM', 'Reward Claim'), ('ROYALTY_PAYOUT', 'Royalty Payout')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('currency', models.CharField(default='MUSIC', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='CONFIRMED', max_length=20)),
                ('from_address', models.CharField(blank=True, max_length=255)),
                ('to_address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
