# Generated by Django 5.2.17 on 2026-09-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallettransaction_tx_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='tx_type',
            field=models.CharField(choices=[('MUSIC_TRANSFER', 'MUSIC Transfer'), ('TICKET_PURCHASE', 'Ticket Purchase'), ('NFT_PURCHASE', 'NFT Purchase'), ('STAKE', 'Stake'), ('UNSTAKE', 'Unstake'), ('REWARD_CLAIM', 'Reward Claim'), ('ROYALTY_PAYOUT', 'Royalty Payout')], max_length=30),
        ),
    ]
