# Generated by Django 5.2.17 on 2026-09-08 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('SONG', 'Song'), ('ALBUM', 'Album'), ('VIP_PASS', 'VIP Pass'), ('COLLECTIBLE', 'Collectible')], default='SONG', max_length=30)),
                ('token_id', models.PositiveIntegerField(blank=True, null=True)),
                ('contract_address', models.CharField(blank=True, max_length=255)),
                ('metadata_uri', models.CharField(max_length=500)),
                ('image_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('royalty_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('royalty_receiver', models.CharField(blank=True, max_length=255)),
                ('tx_hash', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_nfts', to=settings.AUTH_USER_MODEL)),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_nfts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFTListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('FIXED_PRICE', 'Fixed Price'), ('AUCTION', 'Auction')], default='FIXED_PRICE', max_length=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('currency', models.CharField(choices=[('MUSIC', 'MusicCoin'), ('POL', 'Polygon'), ('USDC', 'USDC')], default='MUSIC', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tx_hash', models.CharField(blank=True, max_length=255)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_listings', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='nft.nftitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
