# Generated by Django 5.2.17 on 2026-09-08 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaltySplitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_id', models.CharField(max_length=66, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('contract_address', models.CharField(blank=True, max_length=255)),
                ('total_shares', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_splits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoyaltyRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=255)),
                ('role_name', models.CharField(default='Artist', max_length=100)),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='royalty_recipient_roles', to=settings.AUTH_USER_MODEL)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='royalties.royaltysplitconfig')),
            ],
        ),
        migrations.CreateModel(
            name='RoyaltyPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('currency', models.CharField(default='POL', max_length=10)),
                ('tx_hash', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_history', to='royalties.royaltyrecipient')),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='royalties.royaltysplitconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
