# Generated by Django 5.2.17 on 2026-09-08 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nft_token_id', models.PositiveIntegerField(blank=True, null=True)),
                ('contract_address', models.CharField(blank=True, max_length=255)),
                ('tx_hash', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('CHECKED_IN', 'Checked In'), ('TRANSFERRED', 'Transferred'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=30)),
                ('qr_code_secret', models.CharField(default=uuid.uuid4, max_length=64)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tickets', to='events.tickettier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_scans', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_logs', to='tickets.ticket')),
            ],
        ),
    ]
